In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler

In [2]:
# Read the same raw file EDA used
df = pd.read_csv("../data/processed/laps_2023.csv")

print("Shape of the dataset:", df.shape)

Shape of the dataset: (11255, 33)

In [3]:
pd.set_option("display.max_columns", None)
df.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,SpeedI1,SpeedI2,SpeedFL,SpeedST,IsPersonalBest,Compound,TyreLife,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,RaceName,Year
0,0 days 01:04:15.902000,VER,1,0 days 00:01:39.019000,1.0,1.0,NaN,NaN,NaN,0 days 00:00:42.414000,0 days 00:00:23.842000,NaN,0 days 01:03:52.119000,0 days 01:04:16.010000,232.0,231.0,278.0,252.0,False,SOFT,4.0,False,Red Bull Racing,0 days 01:02:36.652000,NaN,12,1.0,NaN,NaN,False,False,Bahrain,2023
1,0 days 01:05:53.876000,VER,1,0 days 00:01:37.974000,2.0,1.0,NaN,NaN,0 days 00:00:31.342000,0 days 00:00:42.504000,0 days 00:00:24.128000,0 days 01:04:47.303000,0 days 01:05:29.807000,0 days 01:05:53.935000,227.0,238.0,278.0,288.0,True,SOFT,5.0,False,Red Bull Racing,0 days 01:04:15.902000,NaN,12,1.0,NaN,NaN,False,True,Bahrain,2023
2,0 days 01:07:31.882000,VER,1,0 days 00:01:38.006000,3.0,1.0,NaN,NaN,0 days 00:00:31.388000,0 days 00:00:42.469000,0 days 00:00:24.149000,0 days 01:06:25.323000,0 days 01:07:07.792000,0 days 01:07:31.941000,227.0,238.0,278.0,287.0,False,SOFT,6.0,False,Red Bull Racing,0 days 01:05:53.876000,NaN,1,1.0,NaN,NaN,False,True,Bahrain,2023
3,0 days 01:09:09.858000,VER,1,0 days 00:01:37.976000,4.0,1.0,NaN,NaN,0 days 00:00:31.271000,0 days 00:00:42.642000,0 days 00:00:24.063000,0 days 01:08:03.212000,0 days 01:08:45.854000,0 days 01:09:09.917000,228.0,238.0,278.0,289.0,False,SOFT,7.0,False,Red Bull Racing,0 days 01:07:31.882000,NaN,1,1.0,NaN,NaN,False,True,Bahrain,2023
4,0 days 01:10:47.893000,VER,1,0 days 00:01:38.035000,5.0,1.0,NaN,NaN,0 days 00:00:31.244000,0 days 00:00:42.724000,0 days 00:00:24.067000,0 days 01:09:41.161000,0 days 01:10:23.885000,0 days 01:10:47.952000,228.0,239.0,278.0,290.0,False,SOFT,8.0,False,Red Bull Racing,0 days 01:09:09.858000,NaN,1,1.0,NaN,NaN,False,True,Bahrain,2023

In [7]:
# Drop useless columns (100% missing)
df.drop(columns = ["LapStartDate", "Deleted", "DeletedReason"], inplace = True)
df.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,SpeedI1,SpeedI2,SpeedFL,SpeedST,IsPersonalBest,Compound,TyreLife,FreshTyre,Team,LapStartTime,TrackStatus,Position,FastF1Generated,IsAccurate,RaceName,Year
0,0 days 01:04:15.902000,VER,1,0 days 00:01:39.019000,1.0,1.0,NaN,NaN,NaN,0 days 00:00:42.414000,0 days 00:00:23.842000,NaN,0 days 01:03:52.119000,0 days 01:04:16.010000,232.0,231.0,278.0,252.0,False,SOFT,4.0,False,Red Bull Racing,0 days 01:02:36.652000,12,1.0,False,False,Bahrain,2023
1,0 days 01:05:53.876000,VER,1,0 days 00:01:37.974000,2.0,1.0,NaN,NaN,0 days 00:00:31.342000,0 days 00:00:42.504000,0 days 00:00:24.128000,0 days 01:04:47.303000,0 days 01:05:29.807000,0 days 01:05:53.935000,227.0,238.0,278.0,288.0,True,SOFT,5.0,False,Red Bull Racing,0 days 01:04:15.902000,12,1.0,False,True,Bahrain,2023
2,0 days 01:07:31.882000,VER,1,0 days 00:01:38.006000,3.0,1.0,NaN,NaN,0 days 00:00:31.388000,0 days 00:00:42.469000,0 days 00:00:24.149000,0 days 01:06:25.323000,0 days 01:07:07.792000,0 days 01:07:31.941000,227.0,238.0,278.0,287.0,False,SOFT,6.0,False,Red Bull Racing,0 days 01:05:53.876000,1,1.0,False,True,Bahrain,2023
3,0 days 01:09:09.858000,VER,1,0 days 00:01:37.976000,4.0,1.0,NaN,NaN,0 days 00:00:31.271000,0 days 00:00:42.642000,0 days 00:00:24.063000,0 days 01:08:03.212000,0 days 01:08:45.854000,0 days 01:09:09.917000,228.0,238.0,278.0,289.0,False,SOFT,7.0,False,Red Bull Racing,0 days 01:07:31.882000,1,1.0,False,True,Bahrain,2023
4,0 days 01:10:47.893000,VER,1,0 days 00:01:38.035000,5.0,1.0,NaN,NaN,0 days 00:00:31.244000,0 days 00:00:42.724000,0 days 00:00:24.067000,0 days 01:09:41.161000,0 days 01:10:23.885000,0 days 01:10:47.952000,228.0,239.0,278.0,290.0,False,SOFT,8.0,False,Red Bull Racing,0 days 01:09:09.858000,1,1.0,False,True,Bahrain,2023

In [9]:
df.shape

(11255, 30)

#### Features with 100% missing values were dropped cause it carries zero information

---------------------------------------------------------------

In [13]:
# Time related columns 
time_col = [feature for feature in df.columns if ("Time" in feature) or ("Date" in feature)]
print(time_col)
print(len(time_col))

df[time_col].head(10)

['Time', 'LapTime', 'PitOutTime', 'PitInTime', 'Sector1Time', 'Sector2Time', 'Sector3Time', 'Sector1SessionTime', 'Sector2SessionTime', 'Sector3SessionTime', 'LapStartTime']
11

,Time,LapTime,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,LapStartTime
0,0 days 01:04:15.902000,0 days 00:01:39.019000,NaN,NaN,NaN,0 days 00:00:42.414000,0 days 00:00:23.842000,NaN,0 days 01:03:52.119000,0 days 01:04:16.010000,0 days 01:02:36.652000
1,0 days 01:05:53.876000,0 days 00:01:37.974000,NaN,NaN,0 days 00:00:31.342000,0 days 00:00:42.504000,0 days 00:00:24.128000,0 days 01:04:47.303000,0 days 01:05:29.807000,0 days 01:05:53.935000,0 days 01:04:15.902000
2,0 days 01:07:31.882000,0 days 00:01:38.006000,NaN,NaN,0 days 00:00:31.388000,0 days 00:00:42.469000,0 days 00:00:24.149000,0 days 01:06:25.323000,0 days 01:07:07.792000,0 days 01:07:31.941000,0 days 01:05:53.876000
3,0 days 01:09:09.858000,0 days 00:01:37.976000,NaN,NaN,0 days 00:00:31.271000,0 days 00:00:42.642000,0 days 00:00:24.063000,0 days 01:08:03.212000,0 days 01:08:45.854000,0 days 01:09:09.917000,0 days 01:07:31.882000
4,0 days 01:10:47.893000,0 days 00:01:38.035000,NaN,NaN,0 days 00:00:31.244000,0 days 00:00:42.724000,0 days 00:00:24.067000,0 days 01:09:41.161000,0 days 01:10:23.885000,0 days 01:10:47.952000,0 days 01:09:09.858000
5,0 days 01:12:25.879000,0 days 00:01:37.986000,NaN,NaN,0 days 00:00:31.341000,0 days 00:00:42.632000,0 days 00:00:24.013000,0 days 01:11:19.293000,0 days 01:12:01.925000,0 days 01:12:25.938000,0 days 01:10:47.893000
6,0 days 01:14:03.900000,0 days 00:01:38.021000,NaN,NaN,0 days 00:00:31.290000,0 days 00:00:42.763000,0 days 00:00:23.968000,0 days 01:12:57.228000,0 days 01:13:39.991000,0 days 01:14:03.959000,0 days 01:12:25.879000
7,0 days 01:15:42.054000,0 days 00:01:38.154000,NaN,NaN,0 days 00:00:31.291000,0 days 00:00:42.833000,0 days 00:00:24.030000,0 days 01:14:35.250000,0 days 01:15:18.083000,0 days 01:15:42.113000,0 days 01:14:03.900000
8,0 days 01:17:20.332000,0 days 00:01:38.278000,NaN,NaN,0 days 00:00:31.336000,0 days 00:00:42.823000,0 days 00:00:24.119000,0 days 01:16:13.449000,0 days 01:16:56.272000,0 days 01:17:20.391000,0 days 01:15:42.054000
9,0 days 01:18:58.701000,0 days 00:01:38.369000,NaN,NaN,0 days 00:00:31.361000,0 days 00:00:42.884000,0 days 00:00:24.124000,0 days 01:17:51.752000,0 days 01:18:34.636000,0 days 01:18:58.760000,0 days 01:17:20.332000

In [15]:
# Convert timedelta ----> seconds


# Strip column name incase of hidden space
df.columns = df.columns.str.strip()

for col in time_col:
    df[col]= pd.to_timedelta(df[col], errors = "coerce").dt.total_seconds()

df[time_col].head()

,Time,LapTime,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,LapStartTime
0,3855.902,99.019,NaN,NaN,NaN,42.414,23.842,NaN,3832.119,3856.010,3756.652
1,3953.876,97.974,NaN,NaN,31.342,42.504,24.128,3887.303,3929.807,3953.935,3855.902
2,4051.882,98.006,NaN,NaN,31.388,42.469,24.149,3985.323,4027.792,4051.941,3953.876
3,4149.858,97.976,NaN,NaN,31.271,42.642,24.063,4083.212,4125.854,4149.917,4051.882
4,4247.893,98.035,NaN,NaN,31.244,42.724,24.067,4181.161,4223.885,4247.952,4149.858

In [17]:
print(df[time_col].dtypes)

Time                  float64
LapTime               float64
PitOutTime            float64
PitInTime             float64
Sector1Time           float64
Sector2Time           float64
Sector3Time           float64
Sector1SessionTime    float64
Sector2SessionTime    float64
Sector3SessionTime    float64
LapStartTime          float64
dtype: object

--------

In [20]:
# Fix categorical vs numerical cols
categorical_numeric = ["DriverNumber", "Year", "Position", "TrackStatus"]

print(df[categorical_numeric].dtypes, "\n\n")


for col in categorical_numeric:
    df[col] = df[col].astype("category")

print(df[categorical_numeric].dtypes, "\n")

DriverNumber      int64
Year              int64
Position        float64
TrackStatus       int64
dtype: object


DriverNumber    category
Year            category
Position        category
TrackStatus     category
dtype: object

In [22]:
# Fix boolean cols
bool_cols = [feature for feature in df.columns if df[feature].dtype == "bool"]

print(bool_cols, "\n")

# IsPersonalBest is a bool value but stored as an object 
bool_cols.append("IsPersonalBest")
print(bool_cols, "\n\n")


for col in bool_cols:
    df[col] = df[col].map({
        True: True,
        False: False,
        "True": True, 
        "False": False,
        None: pd.NA,
        "nan": pd.NA
    })
    df[col] = df[col].astype("bool")




print(df[bool_cols].head())
print(df[bool_cols].dtypes)

['FreshTyre', 'FastF1Generated', 'IsAccurate']

['FreshTyre', 'FastF1Generated', 'IsAccurate', 'IsPersonalBest']


   FreshTyre  FastF1Generated  IsAccurate  IsPersonalBest
0      False            False       False           False
1      False            False        True            True
2      False            False        True           False
3      False            False        True           False
4      False            False        True           False
FreshTyre          bool
FastF1Generated    bool
IsAccurate         bool
IsPersonalBest     bool
dtype: object

---------

In [25]:
# Create Target Variable 

# PitInTime contains the time a driver entered the pit lane
# If PitInTime has a value = driver pitted that lap = 1
# If PitInTime is NaN = driver stayed out = 0

df["Pitted"] = df["PitInTime"].notna().astype(int)

print("Pit stop distribution:")
print(df["Pitted"].value_counts())
print(f"\nPit Stop rate: {df['Pitted'].mean():.2f}")

Pit stop distribution:
Pitted
0    10878
1      377
Name: count, dtype: int64

Pit Stop rate: 0.03

In [27]:
# Drop PitInTime and PitOutTime
# We already extracted the signal we need (Pitted column)
# Model must never see these 

df.drop(columns = ["PitInTime", "PitOutTime"], inplace = True)
# inplace = True modifys the existing dataframe directly instead of creating a new one

print("Columns remaining:", df.shape[1])

Columns remaining: 29

In [29]:
df.shape

(11255, 29)

In [31]:
df.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,SpeedI1,SpeedI2,SpeedFL,SpeedST,IsPersonalBest,Compound,TyreLife,FreshTyre,Team,LapStartTime,TrackStatus,Position,FastF1Generated,IsAccurate,RaceName,Year,Pitted
0,3855.902,VER,1,99.019,1.0,1.0,NaN,42.414,23.842,NaN,3832.119,3856.010,232.0,231.0,278.0,252.0,False,SOFT,4.0,False,Red Bull Racing,3756.652,12,1.0,False,False,Bahrain,2023,0
1,3953.876,VER,1,97.974,2.0,1.0,31.342,42.504,24.128,3887.303,3929.807,3953.935,227.0,238.0,278.0,288.0,True,SOFT,5.0,False,Red Bull Racing,3855.902,12,1.0,False,True,Bahrain,2023,0
2,4051.882,VER,1,98.006,3.0,1.0,31.388,42.469,24.149,3985.323,4027.792,4051.941,227.0,238.0,278.0,287.0,False,SOFT,6.0,False,Red Bull Racing,3953.876,1,1.0,False,True,Bahrain,2023,0
3,4149.858,VER,1,97.976,4.0,1.0,31.271,42.642,24.063,4083.212,4125.854,4149.917,228.0,238.0,278.0,289.0,False,SOFT,7.0,False,Red Bull Racing,4051.882,1,1.0,False,True,Bahrain,2023,0
4,4247.893,VER,1,98.035,5.0,1.0,31.244,42.724,24.067,4181.161,4223.885,4247.952,228.0,239.0,278.0,290.0,False,SOFT,8.0,False,Red Bull Racing,4149.858,1,1.0,False,True,Bahrain,2023,0

---

#### Encode Tyre Compounds
#### We encode by durability - how long each compound lasts

```
SOFT = 0 ---> degrades fastest 
MEDIUM = 1 ---> middle 
HARD = 2 ---> most durable 
INTERMEDIATE = 3 --> wet conditions
WET = 4 --> full wet

```

In [35]:
# Map each compound to a number 

compound_map = {
    "SOFT": 0,
    "MEDIUM": 1, 
    "HARD": 2, 
    "INTERMEDIATE": 3, 
    "WET" : 4
}


df["CompoundEncoded"] = df["Compound"].map(compound_map)

# Check for any compounds we missed 
print("Unmapped compounds:", df[df["CompoundEncoded"].isna()]["Compound"].unique())


# Confirm distribution 
print("\nCompound distribution")
print(df.groupby("Compound")["CompoundEncoded"].first())

Unmapped compounds: []

Compound distribution
Compound
HARD            2
INTERMEDIATE    3
MEDIUM          1
SOFT            0
WET             4
Name: CompoundEncoded, dtype: int64

In [37]:
df.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,SpeedI1,SpeedI2,SpeedFL,SpeedST,IsPersonalBest,Compound,TyreLife,FreshTyre,Team,LapStartTime,TrackStatus,Position,FastF1Generated,IsAccurate,RaceName,Year,Pitted,CompoundEncoded
0,3855.902,VER,1,99.019,1.0,1.0,NaN,42.414,23.842,NaN,3832.119,3856.010,232.0,231.0,278.0,252.0,False,SOFT,4.0,False,Red Bull Racing,3756.652,12,1.0,False,False,Bahrain,2023,0,0
1,3953.876,VER,1,97.974,2.0,1.0,31.342,42.504,24.128,3887.303,3929.807,3953.935,227.0,238.0,278.0,288.0,True,SOFT,5.0,False,Red Bull Racing,3855.902,12,1.0,False,True,Bahrain,2023,0,0
2,4051.882,VER,1,98.006,3.0,1.0,31.388,42.469,24.149,3985.323,4027.792,4051.941,227.0,238.0,278.0,287.0,False,SOFT,6.0,False,Red Bull Racing,3953.876,1,1.0,False,True,Bahrain,2023,0,0
3,4149.858,VER,1,97.976,4.0,1.0,31.271,42.642,24.063,4083.212,4125.854,4149.917,228.0,238.0,278.0,289.0,False,SOFT,7.0,False,Red Bull Racing,4051.882,1,1.0,False,True,Bahrain,2023,0,0
4,4247.893,VER,1,98.035,5.0,1.0,31.244,42.724,24.067,4181.161,4223.885,4247.952,228.0,239.0,278.0,290.0,False,SOFT,8.0,False,Red Bull Racing,4149.858,1,1.0,False,True,Bahrain,2023,0,0

-----
------

#### Handling Missing Values

In [41]:
# Check remaining missing values 

missing = df.isnull().sum()
missing_pct = (missing / len(df) * 100). round(2)

missing_df = pd.DataFrame({
    "missing_count": missing,
    "missing_pct": missing_pct
}).sort_values("missing_pct", ascending = False)

print(missing_df[missing_df["missing_count"] > 0])

                    missing_count  missing_pct
SpeedFL                       403         3.58
Sector1SessionTime            252         2.24
Sector1Time                   231         2.05
LapTime                       166         1.47
Sector3SessionTime             90         0.80
Sector3Time                    90         0.80
SpeedST                        27         0.24
Position                       26         0.23
SpeedI2                        26         0.23
SpeedI1                        26         0.23
Sector2SessionTime             26         0.23
Sector2Time                    26         0.23

#### Category 2: LapTime Missing (1,47 %)



#### Remaining categories will be handled later

Laptime is more serious, LapTime is core to almost everything we calculated. If LapTime itself is missing, every feature built from it (LapTimeDelta,
LapTimeRolling3, DegradationFromStintStart) would also be unreliable for that row.

Decision: dropping these columns, we can't reliably reconstruct a missing laptime (under 1.5%)

In [44]:
	
df = df.dropna(subset = ["LapTime"]).copy()
print("Shape after dropping missing LapTime: ", df.shape)

Shape after dropping missing LapTime:  (11089, 30)

In [46]:

print("Pit stop distribution now:")
print(df["Pitted"].value_counts())

Pit stop distribution now:
Pitted
0    10764
1      325
Name: count, dtype: int64

-----
-----

#### Tyre Degradation features 

```
Why we are builiding these features:
the raw data only tells us:

TyreLife = 21
LapTime = 92.3s

But the model needs to understand what's happening over time.
- Is the tyre getting slower?
- How much slower vs when it was new?
- Is the degradation speeding up?

A single lap time number doesn't tell us that. so we need to compare it to previous laps. 
```
##### 1. FEATURE 1: LapTimeDelta

In [ ]:
# Tyre Degradation Features 
# Features that tell the model what's happening to the tyres RIGHT NOW


# Sort by race -> driver -> stint -> lap number 
# This ensures laps are in chronological order 
# per driver per stint

df = df.sort_values(
    ["RaceName", "Driver", "Stint", "LapNumber"]
).reset_index(drop = True)

print("Data sorted correctly")
df[["RaceName", "Driver", "Stint", "LapNumber", "LapTime"]].head()

In [ ]:

# LapTimeDelta 
# How much slower is this lap compared to the previous lap?
# Captures : is the tyre degrading RIGHT NOW?

#.diff() calculates the difference between current row and the previous row 
# We group by Race + Driver + Stint so we don't calculate delta across different stints or different drivers


# Positive = getting slower = tyre degrading 
# Negative = getting faster = tyre warming up

# ======== Code before the DATA LEAKAGE =============
"""
df["LapTimeDelta"] = df.groupby(
    ["RaceName", "Driver", "Stint"]
)["LapTime"].diff()

df[["RaceName", "Driver", "Stint", 
    "LapNumber", "LapTime", "LapTimeDelta"]].head(10)
"""

In [ ]:

# Lap 1: 100.6s <- slow, just started, cold tyres
# Lap 2: 93.6s <- much faster, tyres warming up
# Lap 3: 91.7s <- getting faster 
# Lap 4: 91.5s <- peak performance
# Lap 5: 91.4s <- still near peak 


# Tyres start cold, warm up, peak, then slowly degrade.

In [ ]:

# Lap 1: NaN ---> no previous lap to compare, expecte#
# Lap 2: -7.065 --> 7 seconds faster than Lap 1 (tyre warming up)
# Lap 3: -1.792 --> still getting faster
# Lap 4: -0.177 --> nearly stabilized
# Lap 5 - 10 : small fluctuations around 0


# lap 1 is always slow(cold tyres, traffic from pit exit), then the car rapidly
# speeds up as tyres warm up, then it stabilizes.

In [ ]:
# ==== FIX FOR DATA LEAKAGE ====
# Problem: when a driver pits, that lap's LapTime includes driving through
# the pit lane (~ 20 - 25s extra). This creates a massive artificial spike in
# LapTimeDelta on pit laps - not because the tyre degraded, but because the
# pit lane detour inflated the lap's time. The model was learning to detect
# "pit line inflation" rather than genuine tyre degradation



# FIX: temporarily treat pit-lap LapTime as missing (NaN) before calculating
# the diff. This means we never compute a delta INTO an inflated pit lap time,
# so the spike disappears and only genuine degradation patterns remain

#lap_time_for_delta = df["LapTime"].copy()
#print(lap_time_for_delta)

#lap_time_for_delta[df["Pitted"] ==1] = np.nan


#df["LapTimeDelta"] = lap_time_for_delta.groupby(
#    [df["RaceName"], df["Driver"], df["Stint"]]
#).diff()


# Fill remaining Nan (first lap of stint, and the masked pit laps themselves)
# with 0 - meaning "no degradation signal available for this lap"

#df["LapTimeDelta"] = df["LapTimeDelta"].fillna(0)

#df[["RaceName", "Driver", "Stint",
#    "LapNumber", "LapTime", "Pitted", "LapTimeDelta"]].head(15)

In [ ]:
# Since we have substited 0 for the pitted lap (without using NaN)
# verifying whether it will create a bias (another leakage)

# How many ZERO LapTimeDelta values are there overall?
#print("Total LapTimeDelta == 0:", (df["LapTimeDelta"] == 0).sum())

#of those zeros, how many are ACTUALLY pit laps vs not?
#zeros = df[df["LapTimeDelta"]==0]
#print("\nof the rows with LapTimeDelta == 0:")
#print(zeros["Pitted"].value_counts())



#print(f"\n\nPercent of zeros that are pit laps: {(zeros["Pitted"]==1).mean():.2%}")

 ----

```

( this is the outcome of hardcoding 0 )
- 38.01% is way higher than the overall baseline pit rate (~3%).

overall pit rate in whole dataset:    ~3%
Pit rate AMONG rows where delta = 0: ~38%

this means: if the model sees LapTimeDelta = 0, it is now thinks "pit stop is roughly 12x likely than average"


clearner solution: instead of forcing pit laps to exactly 0, we are filling them with something that reflects "we don't have reliable info" without artifically making them resemble each other.
```

In [ ]:
# Better fix: forward fill from the last known good value
# instead of hardcoding 0

lap_time_for_delta = df["LapTime"].copy()
lap_time_for_delta[df["Pitted"] == 1] = np.nan


df["LapTimeDelta"] = lap_time_for_delta.groupby(
    [ df["RaceName"], df["Driver"], df["Stint"]]
).diff()


# Instead of filling NaN with 0, forward fill within each stint
# This means pit laps inherit the LAST GENUINE delta value
df["LapTimeDelta"] = df.groupby(
    ["RaceName", "Driver", "Stint"]
)["LapTimeDelta"].transform(lambda x: x.ffill())

# ANY STILL remaining NaN (genuinely first lap of race, no prior data at all)
# gets filled with 0 as a last resort
df["LapTimeDelta"] = df["LapTimeDelta"].fillna(0)

# Verify
print("LapTimeDelta by Pitted status (forward-fill version):")
print(df.groupby("Pitted")["LapTimeDelta"].describe().T)

---------------
----------------
-----------

In [ ]:
# ======= DIAGNOSE RUNNING ======

# is df index clean and sequenctial after the dropna?
print("df index sample:", df.index[:10].tolist())
print("df index is unique:", df.index.is_unique)
print("Total rows:", len(df))

In [ ]:
# recreate lap_time_delta RIGHT NOW
lap_time_delta = df["LapTime"].copy()
lap_time_delta[df["Pitted"]==1] = np.nan


print("Nan count after masking:", lap_time_for_delta.isna().sum())
print("Should roughly equal to the number of pit stops:", (df["Pitted"] ==1).sum())

In [ ]:
# Pitted value counts
print(df["Pitted"].value_counts())
print(df["Pitted"].dtype)

In [ ]:
test_mask = (df["Pitted"] == 1)
print("True count in mask:", test_mask.sum())
print("Mask dtye:", test_mask.dtype)



test_series = df["LapTime"].copy()
print("test_series index sample:", test_series.index[:5].tolist())
print("test_mask index sample:", test_mask.index[:5].tolist())

print("\n\n")
print("Same index object?", test_series.index.equals(test_mask.index))

test_series[test_mask] = np.nan
print("Nan count after masking:", test_series.isna().sum())

In [ ]:
import numpy
print(np is numpy)
print(type(np.nan))

-----
------
-----

In [ ]:
# How many ZERO LapTimeDelta values are there overall?
print("Total LapTimeDelta == 0:", (df["LapTimeDelta"] == 0).sum())

#of those zeros, how many are ACTUALLY pit laps vs not?
zeros = df[df["LapTimeDelta"]==0]
print("\nof the rows with LapTimeDelta == 0:")
print(zeros["Pitted"].value_counts())



print(f"\n\nPercent of zeros that are pit laps: {(zeros["Pitted"]==1).mean():.2%}")

##### 2. FEATURE 2: LapTimeRolling

In [ ]:
# Average lap time over the LAST 3 laps
# Captures: what is the underlying pace right now?
# Why 3 laps: One bad lap could be traffic or a yellow flag, averaging 3 laps smooths out that noise


# === CODE BEFORE DATA LEAKAGE ==========

#df["LapTimeRolling3"] = df.groupby(
#    ["RaceName", "Driver", "Stint"]
#)["LapTime"].transform(
#    lambda x: x.rolling(window = 3, min_periods = 1).mean()

#)

#df[["Driver", "Stint", "LapNumber",
#    "LapTime", "LapTimeRolling3"]].head(10)

```

Lap 1: 100.625 --> just lap 1 alone (only 1 data point so far)
Lap 2: 97.09 --> average of laps 1 - 2
Lap 3: 95.32 --> average of laps 1 - 3
Lap 4: 92.31 --> average of laps 2- 4 (rolling window of 3)

--- by lap 5 onwards it's hovering around 91.5, which matches the stabilized pace

```

In [ ]:
# LapTimeRolling3 - Fixed for data leakage
# Same fix as LapTimeDelta:
# exclude pit - lap inflated times from the rolling average
lap_time_clean = df["LapTime"].copy()
lap_time_clean[df["Pitted"] == 1] = np.nan

df["LapTimeRolling"] = lap_time_clean.groupby(
    [df["RaceName"], df["Driver"], df["Stint"]]
).transform(lambda x : x.rolling(window = 3, min_periods = 1).mean())



# Forward - fill pit laps with the last genuine rolling average
df["LapTimeRolling"] = df.groupby(
    ["RaceName", "Driver", "Stint"]
)["LapTimeRolling"].transform(lambda x: x.ffill())


# Last resort fill
df["LapTimeRolling"] = df["LapTimeRolling"].fillna(df["LapTime"])


print("LapTimRolling by Pitted status:")
print(df.groupby("Pitted")["LapTimeRolling"].describe().T)

In [ ]:
print(df["LapTime"].head(10))
print(df["LapTime"].dtype)

##### 3. FEATURE 3: DegradationFromStintStart

In [ ]:
# How much slower are we NOW vs lap 1 of this stint?
# Captures: TOTAL Performance loss on this tyre set 
# eg:  +3.2s means 3.2 seconds slower than when tyre was fresh

# CODE BEFORE DATA LEAKAGE ===============

#df["DegradationFromStintStart"] = df.groupby (
#    ["RaceName", "Driver", "Stint"]
#)["LapTime"].transform(
#    lambda x: x - x.iloc[0]
#)

#df[["Driver", "Stint", "LapTime",
#    "LapTime", "DegradationFromStintStart"]].head(10)

In [ ]:
# Instead of comparing to lap 1 of the stint (which is artificially slow), compare to 
# lap 3 of the stint, by then the tyre has warmed up and we get a 
# true degradation baseline

"""

def cal_degradation(group):
    # Use lap 3 as baseline if it exists, otherwise fall back to first available lap
    # This skips the slow out-lap(lap1) and warm-up lap (lap2)

    if len(group) >=3:
        baseline = group.iloc[2] #3rd lap of the stint
    else:
        baseline = group.iloc[0]

    return group - baseline



df["DegradationFromStintStart"] = df.groupby(
    ["RaceName", "Driver", "Stint"]
)["LapTime"].transform(cal_degradation)


df[df["Driver"] == "ALB"][["LapNumber", "LapTime", "DegradationFromStintStart"]].head(15)


"""

```
Laps 1-2   → warming up (slow → fast)
Laps 3-9   → peak performance window (fastest laps)
Laps 10+   → degradation creeping in (numbers trending positive)
```

```
Lap 1 was slow cause of the cold tyres, so every lap after looks "faster" relative to that slow start.

but this isn't capturing true degradation yet, we typically exclude the out-lap when measuring degradation and start the 'stint start' reference from lap 2 or 3 once the tyre has actually warmed up.
```

In [ ]:
# FIXING THE DATA LEAKAGE ================

lap_time_clean2 = df["LapTime"].copy()
lap_time_clean2[df["Pitted"] == 1] = np.nan

def cal_degradation(group):
    valid = group.dropna()
    if len(valid) >= 3:
        baseline = valid.iloc[2]
    elif len(valid) > 0:
        baseline = valid.iloc[0]
    else:
        return group * np.nan
    return group - baseline


df["DegradationFromStintStart"] = lap_time_clean2.groupby(
    [df["RaceName"], df["Driver"], df["Stint"]]
).transform(cal_degradation)


# Forward- fill pit laps with last genuine degradation value
df["DegradationFromStintStart"] = df.groupby(
    ["RaceName", "Driver", "Stint"]
)["DegradationFromStintStart"].transform(lambda x: x.ffill())

df["DegradationFromStintStart"] = df["DegradationFromStintStart"].fillna(0)

In [ ]:
print("LapTimeDelta by Pitted status:")
print(df.groupby("Pitted")["LapTimeDelta"].describe().T)
print("\n\n")


print("LapTimgRolling by Pitted status: ")
print(df.groupby("Pitted")["LapTimeRolling"].describe().T)
print("\n\n")

print("DegradationFromStintStart by Pitted status:")
print(df.groupby("Pitted")["DegradationFromStintStart"].describe().T)

In [ ]:
df.head()

In [ ]:
# ======= DIAGNOSE THE ISSUE ===========

# Checking lap_time_for_delta BEFORE any masking
print("Sample LapTime value:")
print(df["LapTime"].head(10))
print("\n\n")


# Recreate lap_time_for_delta
lap_time_for_delta = df["LapTime"].copy()
print("\nlap_time_for_delta before masking:")
print(lap_time_for_delta.head(10))

# Apply the pit mask, checking again
lap_time_for_delta[df["Pitted"] == 1] = np.nan
print("\nlap_time_for_delta after masking pit laps: ")
print(lap_time_for_delta.head(10))

In [ ]:
# Telemetry Leakage FIX =================
# Sector time, Speeds


# Fix telemetry leakage - same root cause as LapTime contamination
# Sector times and speed traps are also affected by the lap lane detour
# mandatory speed limit, extra distance through pit lane



telemetry_cols_to_fix = ["Sector1Time", "Sector2Time", "Sector3Time",
                         "SpeedI1", "SpeedI2", "SpeedFL", "SpeedST"]

for col in telemetry_cols_to_fix:
    masked = df[col].copy()
    masked[df["Pitted"] == 1] = np.nan


    df[col] = masked.groupby(
        [df["RaceName"], df["Driver"], df["Stint"]]
    ).transform(lambda x : x.ffill())
    df[col] = df[col].fillna(df[col].median())


print("Telemetry columns fixed for leakage")
for col in telemetry_cols_to_fix:
    print(f"\n{col} by Pitted status (after fix):")
    print(df.groupby("Pitted")[col].describe()[["mean", "std", "min", "max"]])

----

#### Race Context Features

In [ ]:
# Drivers with multiple stints
# Check what happens to LapNumber vs TyreLife across a pit stop

sample_driver = df[df["Driver"] == "ALB"]
sample_driver[["LapNumber", "Stint", "TyreLife"]].head(10)

#### Feature 1: RacePctComplete

```

- Races have different lengths. Monaco is 78 laps, Spa is 44 laps. If the model just sees
LapNumber = 40,
it doesn't know if that's early or late. 40 out of 78 is very different to 40 out of 44

by converting to a percentage, the model can compare across different races on the same scale. Lap 40 of 44 (91% done) means something totally different from lap 40 of 78(51% done)

``

In [ ]:
# Creating TotalLaps 

# For each race, find the maximum LapNumber any driver reaches 

df["TotalLaps"] = df.groupby("RaceName")["LapNumber"].transform("max")

df[["RaceName", "LapNumber", "TotalLaps"]].head(10)

In [ ]:
df.groupby("RaceName")["TotalLaps"].unique()

In [ ]:
# Feature 1: RacePctComplete

df["RacePctComplete"] = df["LapNumber"] /df["TotalLaps"]
df["RacePctComplete"].head()

#### Feature 2: LapsRemaining

```
the absolute number of laps. There is a real, practial difference between "7 laps left"
and "21 laps left" even if they are the same percentage on different length races.

why this matters:
pitting costs roughly 20 -25 seconds (driving into the pits, the stop itself, driving bak out). If there's only 3 laps left, you mathematically cannot make up the time loss even on fresh tyres. so the model needs to know the actual lap count to learn this cutoff behaviour.

```

In [ ]:
df["LapsRemaining"] = df["TotalLaps"] - df["LapNumber"]
df.head()

#### Feature 3: IsLateRace

```

What it is: simple flag, are we in the final 30% of th race, 1 if yes,  0 if no .


This is called a binary flag feature and it helps the model in a specific way.
- Tree based models like "XGBoost can already learn threshold on their own.
- But giving it an explicity pre- computed flag at a sensible threshold (0.7 based on f1- domain knowledge, strategies usually get aggresive in the last third). makes that pattern easier and faster for the model to pick up, especially with limited data.



Why 0.7 specifically:
- in f1, the final ~30% of a race is when 'undercut' and 'overcut' strategic battles intensify. safety car gambles get riskier to pass up and the teams start taking more aggresive decisions. We picked 0.7 based on the race strategy knowledge, It is somewhat arbitrary, and we could experiment with 0.65 or 0.75 later to see if it changes model performance

```

In [ ]:
df["IsLateRace"] = (df["RacePctComplete"]> 0.7).astype(int)
df.head()

In [ ]:
df["IsLateRace"].unique()

----

In [ ]:
# Dropping the useless columns


# DRIVER --> identity columns - model shouldn't learn from WHO is driving 
# (model learns from BEHAVIOUR, not IDENTITY)

cols_to_drop = ["DriverNumber", "TrackStatus"]

# Add Team too
if "Team" in df.columns:
    cols_to_drop.append("Team")

df.drop(columns = cols_to_drop, inplace = True)

print("Dropped", cols_to_drop)
print("Remaining columns: ",
      df.shape[1])

In [ ]:
print(df["Year"].unique())

In [ ]:
# Dropping the "Year"


df.drop(columns =["Year"], inplace = True)

In [ ]:
df.head()

----

#### Category 1 : Sector times and speeds (low missingness , <5%)

Decision : fill with median

In [ ]:
sector_speed_cols = [
    "SpeedFL", "Sector1SessionTime", "Sector1Time", 
    "Sector3Time", "Sector3SessionTime", "SpeedST",
    "Sector2Time", "Sector2SessionTime", "SpeedI2", "SpeedI1"
]

for col in sector_speed_cols:
    if col in df.columns:
        median_val = df[col].median()
        df[col] = df[col].fillna(median_val)

print("Sector/speed columns filled with median")

#### Position: fill with forward fill instead, since position should logically follo from the previous lap.

In [ ]:
df["Position"].dtypes

In [ ]:
df["Position"] = df.groupby(["RaceName", "Driver"])["Position"].ffill()

# catch any remaining edge cases (very first lap of the race)
#df["Position"] = df["Position"].fillna(df["Position"].median())

In [ ]:
df = df.dropna(subset = ["LapTime"]).copy()
print("Shape after dropping missing LapTime: ", df.shape)

#### Category 3: Engineered features (LapTimeDelta, LapTimeRolling3, DegradationFromStintStart)

1. Natural NaN - first lap of every stint( no prev lap to diff against)
2. Cascading NaN = caused by the LapTime rows we just dropped or other upstream issues

In [ ]:
# Fill remaining NaN with 0 meaning:
# no detected change for the first lap

df["LapTimeDelta"] = df["LapTimeDelta"].fillna(0)
df["LapTimeRolling"] = df["LapTimeRolling"].fillna(df["LapTime"])
df["DegradationFromStintStart"] = df["DegradationFromStintStart"].fillna(0)

In [ ]:
# Final check
final_missing = df.isnull().sum()
print(final_missing[final_missing > 0])

print("\nTotal missing values remaining:" , df.isnull().sum().sum())
print("Final shape ", df.shape)

----

#### Check Multicollinearity

- when two features are so correlated with each other that they carry almost the same information.
- This confuses linear models like logistic regression because it can't tell which one is actually driving the prediction.

In [ ]:
# Select only numeric cols for correlation check
numeric_cols = df.select_dtypes(include = [np.number]).columns.tolist()

# Remove the target variable 
numeric_cols = [col for col in numeric_cols if col != "Pitted"]

corr_matrix = df[numeric_cols].corr()

plt.figure(figsize = (14, 10))
sns.heatmap(corr_matrix, cmap = "coolwarm", center = 0, annot = False)
plt.title("Correlation Matrix - looking for multicollinearity")
plt.show()

In [ ]:
# Find the pairs with correlation above 0.85 (high multicillinearity)

threshold = 0.85
high_corr_pair = []


for i in range(len(corr_matrix)):
    for j in range (i +1, len(corr_matrix)):
        col1 = corr_matrix.columns[i]
        col2 = corr_matrix.columns[j]
        corr_val = corr_matrix.iloc[i, j]
        if abs(corr_val) > threshold:
            high_corr_pair.append((col1, col2, round (corr_val, 3)))


print("Highly correlated pairs (potential multicollinearity): ")
for pair in high_corr_pair:
    print(pair)

#### Family 1: "Time": cols ( all measure the same thing : race progress)

Time, LapStartTime, Sector1/2/3SessionTime, LapNumber, RacePctComplete, LapsRemaining

Decision: we drop everything else but the Engineered features

In [ ]:
cols_to_drop = [
    "Time", "LapStartTime",
    "Sector1SessionTime", "Sector2SessionTime", "Sector3SessionTime",
    "LapNumber"]

df_logreg = df.drop(columns = cols_to_drop, errors = "ignore")
print("Dropped columns: ", cols_to_drop)
print("Remaining shape: ", df_logreg.shape)

#### Family 2: LapTime vs LapTimeRolling3 (0.929)

Decision: Drop LapTime itself for logistic regresion, keep LapTimeRolling3, since it is the smoothed, less noisy version

In [ ]:
df_logreg = df_logreg.drop(columns = ["LapTime"], errors = "ignore")

In [ ]:
# Final Multicollinearity check 

numeric_cols_logreg = df_logreg.select_dtypes(include = [np.number]).columns.tolist()
numeric_cols_logreg = [col for col in numeric_cols_logreg if col != "Pitted"]

corr_matrix_final = df_logreg[numeric_cols_logreg].corr()

high_corr_remaining = []

for i in range(len(corr_matrix_final.columns)):
    for j in range(i+1, len(corr_matrix_final.columns)):
        corr_val = corr_matrix_final.iloc[i, j]
        if abs(corr_val) > 0.85:
            high_corr_remaining.append((
                corr_matrix_final.columns[i],
                corr_matrix_final.columns[j],
                round(corr_val, 3)

            ))

print("Remaining high correlation pairs: :", high_corr_remaining)
print("\nFinal shape for logistic regression: ", df_logreg.shape)

---

#### Scaling/ Normalising features (for logistic regression)

- logistic regression uses gradient descent to learn, and it's sensitive to features being on different scales. A feature like LapTimeRolling3 (ranging ~85 - 110) would dominate over RacePctComplete (ranging 0-1) purely cause ot its bigger numbers, not becaus eof the significance

In [ ]:
# Seperate features (X) from the target (y) for logreg dataset
# Exclude non-numeric / non-feature cols too

exclude_cols = ["Pitted", "Driver", "RaceName", "Compound"]

feature_cols_logreg = [col for col in df_logreg.columns if col not in exclude_cols]
feature_cols_logreg = df_logreg[feature_cols_logreg].select_dtypes(include = [np.number]).columns.tolist()

# Remove IsLateRace (binary flag, shouldn't be scaled)
feature_cols_logreg = [col for col in feature_cols_logreg if col != "IsLateRace"]

print("Position in list now?", "Position" in feature_cols_logreg)
print("Final columns to scale:", feature_cols_logreg)

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df_logreg[feature_cols_logreg] = scaler.fit_transform(df_logreg[feature_cols_logreg])

print(df_logreg[feature_cols_logreg].describe().T)

In [ ]:
# Calculating average tyre age (HIGH_TYRE_AGE)
pit_laps = df[df["Pitted"] ==1]
print(pit_laps["TyreLife"].mean())

In [ ]:
# HIGH_DEGRADATION_DELTA = 

pit_window = df[df["Pitted"] ==1]["LapTimeDelta"]
print(pit_window.describe())

print(f"Median delta at pit: {pit_window.median():.3f}")

In [ ]:
# HIGH TOTAL DEGRADATIOM
# what's the actual degradation at the point drivers pit?
pit_degradation = df[df["Pitted"]==1]["DegradationFromStintStart"]
print(pit_degradation.describe())

print(f"Median degradation at pit: {pit_degradation.median():.3f}")

In [ ]:
# Save both versions

# for XGBoost
df.to_csv("../data/processed/features_2023.csv", index =False)
print(f"XGBoost dataset shape: {df.shape}")

In [ ]:
# For Logistic Regression 
df_logreg.to_csv("../data/processed/features_2023_scaled.csv", index = False)

print(f"Logistic Regression dataset shape: {df_logreg.shape}")